cmd/deploy.go
cmd/galaxy.go
cmd/galaxy_install.go
cmd/info.go
cmd/provision.go
cmd/rollback.go
main.go
trellis/trellis.go

This refactors most of the detection and loading of a Trellis project.
The main bug in the original implementation was the use of `os.Chdir` as
the detect function traversed up the directory tree. When no project was
detected, the working directory was still changed to a root directory.
This likely wouldn't have the proper permissions, but even if it did,
the path the project was created at would be entirely wrong.
Now `os.Chdir` only happens when a valid Trellis project is actually
detected. This also only happens now for commands which need to act on a
project and call `LoadProject` explicitly.

Fix #8 - Refactor project detection

---

cmd/info.go
cmd/new.go
go.mod
go.sum
main.go
test-fixtures/trellis/group_vars/development/vault.yml
test-fixtures/trellis/group_vars/development/wordpress_sites.yml
test-fixtures/trellis/group_vars/production/vault.yml
test-fixtures/trellis/group_vars/production/wordpress_sites.yml
trellis/config.go
trellis/config_test.go
trellis/trellis.go
trellis/vault.go
trellis/vault_test.go

`new` command will update default wordpress_sites and vault config files including generating all needed salts/passwords.

Generate configs during project creation

---

cmd/new.go
go.mod
main.go

`new` will not be a frequent command and this makes the CLI arguments more confusing.
Now it prompts for project name + site host. Colours have been added for better output as well.

Improve new project prompts

---

cmd/new.go
main.go
trellis/config.go
trellis/trellis.go
trellis/vault.go

Example:
```
Created by trellis-cli v0.2.1
Documentation: https://roots.io/trellis/docs/wordpress-sites/
```
trellis-cli was stripping the default comments in `vault.yml` and
`wordpress_sites.yml`. While this doesn't restore the default ones, it
provides a docs URL and lets the user know that it was created by
trellis-cli and the version.

Add Yaml comment headers to configs

---

trellis/vault.go

Special characters can cause issues in a few places:
* YAML files/templates
* Certain commands/software such as Ansible's `mysql_db`
While it may seem less secure to generate passwords without these
characters (ie: easier to brute-force), password length is still the most
important factor. Special characters are often used to ensure *human*
created passwords have more entropy (less random); however, these
strings are cryptographically randomly generated so they don't suffer
from these human issues.
So this should cause less isuess while still being secure enough for our
use cases.
Caveat: I don't really know anything about cryptography.

Fix #32 - Remove special chars from random strings

---

cmd/deploy.go
cmd/deploy_test.go
trellis/testing.go

Fixes #29 
If a Trellis project only has one site for an environment, the `SITE` argument can be left off.

Deploy: only require SITE if there's more than one

---

cmd/vault.go
cmd/vault_decrypt.go
cmd/vault_decrypt_test.go
cmd/vault_encrypt.go
cmd/vault_encrypt_test.go
trellis/complete_test.go
trellis/testdata/trellis/group_vars/all/vault.yml
trellis/testdata/trellis/group_vars/production/encrypted.yml
trellis/testing.go

Fixes #42
This makes both `vault encrypt` and `vault decrypt` idempotent and more user friendly.
`ansible-vault` returns errors if you try to encrypt already encrypted files (or decrypt already decrypted files) which is annoying. Now these cases will be handled without errors by testing ahead of time the state of files.

Improve vault encrypt/decrypt commands

---

cmd/new.go

Ref: #31
Previously running `trellis new foo` would just panic with an exception because it was assumed `foo` would be a domain name and fail during parsing.
The least we can do for now is handle this case and output a proper and helpful error message.

Improve error for invalid name/path in new command

---

cmd/deploy.go
cmd/deploy_test.go
cmd/rollback.go
cmd/rollback_test.go

`deploy` supported using the first site as a default while `rollback`
did not. This adds support for that to `rollback` for consistency. Both
also have validation for the SITE argument now.
Tests have also been improved and made consistent.

Improves site usage for deploy and rollback

---

Dockerfile
cmd/galaxy_install.go
cmd/galaxy_install_test.go

From `requirements.yml` to `galaxy.yml` as per Trellis v1.1.0 (specifically roots/trellis#1100).
It’s probably preferable to have it set the file name based on the Trellis version, since this change alone would break compatibility with Trellis versions prior to 1.1.0.

Rename Ansible role file for `galaxy install` cmd

---

cmd/galaxy_install.go
cmd/galaxy_install_test.go

Adds backwards compatibility for `galaxy install` to support either
`requirements.yml` or `galaxy.yml`

Galaxy install: handle both role files

---

cmd/dot_env.go
cmd/ioutil.go
go.mod
templates/dotenv_yml.go
templates/trim_space.go

```sh-session
$ brew install --HEAD roots/tap/trellis-cli-dev
$ trellis dotenv
2019/09/05 21:27:26 open /private/tmp/trellis-cli-dev-20190905-22385-yw2rrn/playbooks/dotenv.yml: no such file or directory
```
```sh-session
// See: https://github.com/TangRufus/homebrew-tap/blob/fae621d855a80f1a8511f0889d709ede3ff46cdf/Formula/trellis-cli-dev.rb
$ brew install --HEAD tangrufus/tap/trellis-cli-dev
$ trellis dotenv
// work as expected
```
---
Related: https://github.com/roots/trellis-cli/pull/52#issuecomment-527461514

Embed playbook file

---

cmd/alias.go
cmd/alias_test.go
cmd/dot_env.go
cmd/environment_variable.go
cmd/testdata/expected/alias/wp-cli.trellis-alias.yml
main.go
templates/alias_copy_yml.go
templates/alias_yml.go
templates/alias_yml_j2.go

Generate WP CLI aliases for remote environments. See: https://github.com/ItinerisLtd/cognomen/issues/3#issuecomment-456563138
Ported from https://github.com/ItinerisLtd/cognomen/tree/88f77e416da8cb6bdb48deee430b9ccf4a7a486e

Add `alias` command

---

trellis/trellis.go

It turns out that the cli package runs all command autocomplete functions at boot. Since many command's autocomplete functions try to load a Trellis project, this means it attempts to load a project many times.
Checking if `Path` has been previously set speeds up runtime by about 50%!
Before: `trellis info  0.02s user 0.02s system 100% cpu 0.044 total`
After: `trellisinfo  0.01s user 0.01s system 87% cpu 0.025 total`

Skip loading an already loaded project

---

cmd/exec.go
cmd/exec_test.go
cmd/init.go
cmd/init_test.go
cmd/main.go
cmd/new.go
github/main.go
main.go
trellis/detect.go
trellis/detect_test.go
trellis/trellis.go
trellis/virtualenv.go
trellis/virtualenv_test.go

trellis-cli exists to make Trellis easier to install, use, and manage. So far all the features have made it easier to create new projects and manage them, but nothing to help install Trellis' initial requirements. We've seen people struggle to use the proper python, install `pip`, install the correct versions of Ansible, etc.
This PR adds [virtualenv](https://virtualenv.pypa.io/en/latest/) support which is a tool to create isolated Python environments. The idea is that a Trellis user *only* needs Python installed and trellis-cli will take care of the rest. Thankfully most OS' have Python installed by default, so nothing else will be needed.
High-level workflow:
1. when creating a project with `new`, a virtualenv is created per project and activated
2. a new `init` command will …

Virtualenv support

---

.circleci/config.yml
Dockerfile
README.md

To fix [gorelaser not building error](https://circleci.com/gh/roots/trellis-cli/108?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Note: We need to publish new docker image after merging into master

Bump golang to v1.13

---

.goreleaser.yml

This is because `syscall.Exec` doesn't work on windows and `sys/unix.Exec` doesn't have a windows counterpart. See: https://github.com/roots/trellis-cli/pull/64
Until someone smarter than me make [`SyscallCommandExecutor`](https://github.com/roots/trellis-cli/blob/cb5abb0c32042c67567f476f22fb7afbbff4f89a/cmd/command.go#L16) works on windows, use WSL instead. 
Sorry windows users.

Remove windows support

---

.circleci/config.yml

Redeem from https://github.com/roots/trellis-cli/pull/67 (golang version was not the issue).
This pull request adds `goreleaser check` and `goreleaser --snapshot --skip-publish --rm-dist` to check compilation issues.
The command is taken from https://goreleaser.com/quick-start/
> You can test the configuration at any time by running GoReleaser with a few extra parameters to not require a version tag, skip publishing to GitHub, and remove any already-built files:
>    $ goreleaser --snapshot --skip-publish --rm-dist
> -- https://goreleaser.com/quick-start/

CircleCI: Dry run `goreleaser`

---

trellis/virtualenv.go

Previously this selected python3's built-in `venv` feature first if python3 is detected.
Now this will select `virtualenv` first if installed. This gives users more control and allows them to specify a python version via the `VIRTUALENV_PYTHON` env var which `virtualenv` supports.
This is one solution to the issue encountered in https://discourse.roots.io/t/ansible-upgrade-breaks-access-to-all-other-trellis-deploys/16733/16

Default to virtualenv if installed

---

trellis/virtualenv.go
trellis/virtualenv_test.go

`$PATH` isn't expanded as usual so instead this just uses the actual full value we already have.

Fix virtualenv PATH env var

---

Makefile

Tests weren't running if trellis-cli directory is in another directory with spaces in the name.

Quote pwd in Makefile

---

cmd/new.go

It's just a bit more succinct, eh?

Use fmt.Errorf to create formatted error string

---

cmd/deploy.go
cmd/deploy_test.go
main.go

We should use `ansible-playbook deploy.yml` directly instead of going through `bin/deploy.sh`. Eventually that deploy script will be removed entirely from Trellis and users should use this CLI.
This also adds support for extra vars.

Use ansible-playbook for deploy command

---

trellis/trellis.go

Stat returns nil for error if file exists, so that check will never run, removing it keeps the same functionality.

Remove unreachable file existence check

---

cmd/deploy.go
cmd/rollback.go
cmd/ssh.go
trellis/trellis.go
trellis/trellis_test.go

- Extract `func (t *Trellis) FindSiteNameFromEnvironment(environment string, siteNameArg string) (string, error) {`
- Normalize error message

Extract `func (t *Trellis) FindSiteNameFromEnvironment(environment string, siteNameArg string) (string, error) {`

---

README.md
cmd/db.go
cmd/db_open.go
cmd/db_opener_factory.go
cmd/db_opener_factory_test.go
cmd/db_opener_sequel_pro.go
cmd/db_opener_sequel_pro_test.go
cmd/db_opener_tableplus.go
cmd/db_opener_tableplus_test.go
main.go

Open remote databases via SSH tunnels in your favourite database client.
An database client on your local machine registered as `mysql+ssh://` handler, e.g: [TablePlus](https://tableplus.com/)
In a nutshell, it invokes this command on your local machine:
```
$ open 'mysql+ssh://web@111.222.333.444:22/my_db_user:my_db_password@localhost/my_db_name?enviroment=production&usePrivateKey=true'
```
I've only tested [TablePlus](https://tableplus.com/).
Sqeual Pro (nightly) supports `mysql://` but seems [not support SSH tunnels yet](https://github.com/sequelpro/sequelpro/issues/1681)
No.
---
See: https://github.com/roots/trellis-cli/issues/7

Add `db open` command

---

cmd/galaxy_install.go

https://github.com/roots/trellis-cli/pull/97#discussion_r368332716

Print the original stderr when first `ansible-galaxy install` fails

---

cmd/deploy.go
cmd/deploy_test.go

These vars aren't being recognized by Ansible due to the quoting.
Looking at the existing deploy.sh script and they aren't quoted in there.
@TangRufus it makes sense for me to fix this first in master since it shouldn't be part of your playbook PR.

Fix deploy args

---

cmd/galaxy_install.go
cmd/galaxy_install_test.go
cmd/main.go

Closes #95 
This will automatically detect roles that are already installed but a different version than specified in the roles file (`galaxy.yml`) and install them for you.
This solves an annoying problem with `ansible-galaxy` because the easier  solution is to run `install --force` but that re-installs *everything* and is slower.

Automatically install Galaxy roles with -f

---

cmd/provision.go

I can't really think of a downside to this considering:
1. the galaxy roles are required to provision
2. subsequent `install` commands are quite fast if roles are already installed (plus provisioning is slow)
This removes the need to manually remember to run `galaxy install` or being confused when provision fails due to a missing role.

Automatically run galaxy install during provision

---

cmd/galaxy_install_test.go
cmd/ssh_test.go
cmd/vault_edit_test.go

See: https://github.com/roots/trellis-cli/pull/100#discussion_r373815271

Refactor tests: Do not use `MockProject` whenever possible

---

trellis/complete.go

These autocomplete functions are called *every* time the binary is run which was calling `LoadProject` in contexts we don't actually care if a project exists or not (like running `trellis help`, or any command which is project independent).
The only situations we actually want a project loaded is when we're autocompleting for the commands which is what will happen now since the checks are *within* the `PredictFunc`.
https://github.com/roots/trellis-cli/pull/65 was my previous "fix" for this but all that did was speed up successive **successful** look ups.

Make autocompletion lazier

---

cmd/new.go
cmd/up.go

Also changes the `up` command to default to skipping galaxy install.
This changes the flag from `--no-galaxy` to `--with-galaxy`.
Since trellis-cli improves `galaxy install` and auto-runs on `provision`
and `new`, it makes sense to avoid the crappy `ansible-galaxy install`
run by Vagrant by default.

Run galaxy install on new project

---

cmd/new.go

Trellis is versioned with `v` on GitHub where as Bedrock is not.

fix(new): Fix double `v` on Trellis version

---

cmd/db_opener_sequel_pro_test.go
cmd/main.go

This uses the ui.Info instead of fmt.Println for consistency. It also means during tests we won't see the "Running program" lines.

Improve logCmd output

---

cmd/shell_init.go
cmd/shell_init_test.go
cmd/venv_hook.go
cmd/venv_hook_test.go
main.go
trellis/hosts_test.go
trellis/trellis.go
trellis/trellis_test.go

trellis-cli automatically creates a Virtualenv for managing Python and its dependencies and it's activated *within* trellis-cli for running commands. If you want to activate the Virtualenv *outside* of trellis-cli (in your shell), it either needs to be activated manually or every command needs to be run through `trellis exec`.
This adds automatic shell integration which will activate the Virtualenv transparently whenever you `cd` into a Trellis project and deactivates whenever you `cd` out of it.
A new `shell-init` command exists which prints out a script specific to your shell; Bash and Zsh are currently supported:
Zsh:
```bash
// Add to `.zshrc`
eval "$(trellis shell-init zsh)" 
```
Bash:
```bash
// Add to `.bash_profile`
eval "$(trellis shell-init bash)" 
```

Add shell hook for auto Virtualenv activation

---

cmd/up.go

exec.Cmd defaults to the current process's environment which is what we almost always want. But in cases when we need to set a command `Env` we can't just append to its own `Env`. We need to explicitly use `os.Environ()` and append to that.

Fixes #121 - Fix `up` cmd environment

---

README.md

Just started checking out the CLI - seems awesome so far!
After adding `eval "$(trellis-cli shell-init zsh)"` to my `.zshrc` file:
```
❯ source ~/.zshrc
/Users/jeremy/.zshrc:117: command not found: trellis-cli
```
After adjusting to `eval "$(trellis shell-init zsh)"`:
```
❯ source ~/.zshrc
[trellis] activated env
```
Great success!
I also adjusted the header levels to hopefully make the hierarchy a little clearer; at first I thought the virtualenv integration was under the manual install header, so I wouldn't need to do it myself (having installed from Homebrew). This part's not as important, so I can also take out of the PR :)

Update command name in README.md

---

.goreleaser.yml
cmd/deploy.go
cmd/deploy_test.go

Fixes https://github.com/roots/trellis-cli/issues/125
Not that this will only work if the Trellis project used has `branch` variable support from https://github.com/roots/trellis/pull/1204. There's no real way to set a dependency on a trellis-cli feature for a Trellis version yet.

Add branch option to deploy

---

cmd/vault_decrypt.go

Fixes #132 which was trying to decrypted non-encrypted files causing it to error and stop.
@TangRufus not 100% sure how to test this properly but the fix is simple away

Fix `vault decrypt <env>` command

---

cmd/new.go
github/main.go
github/main_test.go
go.mod
go.sum
main.go
trellis/virtualenv.go
update/main_test.go

Closes #138 
`--trellis-version` accepts:
- `latest`
- `dev` (HEAD/master)
- or any version/tag
Example:
```bash
$ trellis new --trellis-version=1.7.0 example.com
```

Add trellis version option for `new` command

---

cmd/venv_hook.go
go.mod
go.sum

Without quoting (escaping) paths with spaces (or potentially other special characters) would break the hook script.
cc @jeffbyrnes

Fix #142 - Quote/escape paths in venv hook

---

cmd/init.go
cmd/main.go

Goal: To provide more helpful error messages
Before:
```sh-session
$ trellis init
Creating virtualenv in /Users/rufus/Code/typist/trellis/.trellis/virtualenv
✓ Virtualenv created
✓ Dependencies installed
Error installing pip requirements: exit status 1
```
After:
```sh-session
$ trellis init
Creating virtualenv in /Users/rufus/Code/typist/trellis/.trellis/virtualenv
✓ Virtualenv created
✓ Dependencies installed
Error installing pip requirements: exit status 1
Stack trace:
Requirement already satisfied: ansible<3.0,>=2.8.0 in ./.trellis/virtualenv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (2.10.1)
Requirement already satisfied: passlib in ./.trellis/virtualenv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.7.4)
ERROR: Could not find a version that …
```

`InitCommand`: Show `pip` stack trace when failed

---

cmd/passthrough.go
main.go
main_test.go
plugin/finder.go
plugin/finder_test.go
plugin/help_func.go
plugin/help_func_test.go
plugin/register.go
plugin/register_test.go

Inspired by https://github.com/kubernetes/kubectl/blob/b155278f1f4a21a0be2d4f6f0037258dee4d1a22/pkg/cmd/plugin/plugin.go and https://github.com/kubernetes/kubectl/blob/b155278f1f4a21a0be2d4f6f0037258dee4d1a22/pkg/cmd/cmd.go#L371
To test:
```bash
cd trellis-cli
go build
mkdir testing
ln -s $(which git) ./testing/trellis-git
echo "#\!/bin/bash\necho 'i am plugintest'" > testing/trellis-plugintest
echo "#\!/bin/bash\necho 'i am theplugin subtest'" > testing/trellis-theplugin-subtest
sudo chmod +x testing/trellis-plugintest
sudo chmod +x testing/trellis-theplugin-subtest
PATH="$(pwd)/testing:$PATH" ./trellis-cli
PATH="$(pwd)/testing:$PATH" ./trellis-cli plugintest
PATH="$(pwd)/testing:$PATH" ./trellis-cli theplugin subtest
PATH="$(pwd)/testing:$PATH" ./trellis-cli git …
```

[Help Wanted] Add plugin system (Look for `trellis-*` in `$PATH`)

---

.goreleaser.yml
main.go

Goal: To avoid human mistakes.

Use goreleaser to set version number on build

---

cmd/droplet_create.go
digitalocean/main.go

Fixes #161
Adds the `--image` option flag to the `droplet create` command and bumps the default to `ubuntu-20-04-x64`

Add option for droplet image (default Ubuntu 20.04)

---

cmd/provision.go
cmd/provision_test.go

The `provision` command used to always run the `server.yml` playbook regardless of environment which isn't correct for development where `dev.yml` should be used.
This sets `dev.yml` as the playbook for development and also specifies Vagrant's generated inventory file if it exists. This is needed for Vagrant boxes to use the proper user, host, port and private SSH key.

Fix provision in dev for Vagrant

---

trellis/trellis.go

It's a common use case to start using trellis-cli on an existing Trellis project (meaning the project wasn't created from `trellis new`). In these cases, it's easy to miss that `trellis init` should be run to create a virtualenv and install dependencies.
This adds a warning message whenever a command is run and there's no virtualenv initialized that suggests users run `trellis init`. This is also just a helpful reminder in case someone knows about the init command but forgets, or the virtualenv gets deleted for some reason.
It can be disable by the existing `TRELLIS_VENV` environment variable.

Add warning when project is not initialized

---

cmd/db_open.go
cmd/deploy.go
cmd/dot_env.go
cmd/down.go
cmd/droplet_create.go
cmd/exec.go
cmd/galaxy_install.go
cmd/info.go
cmd/init.go
cmd/provision.go
cmd/rollback.go
cmd/up.go
cmd/vault_decrypt.go
cmd/vault_edit.go
cmd/vault_encrypt.go
cmd/vault_view.go
main.go
trellis/trellis.go
trellis/virtualenv.go

Mainly this avoids showing the newly added warning about the virtualenv not existing while running the `init` command. If the warning tells users to run `trellis init`, then we shouldn't show the warning _again_ once they run it.
This also improves the output a bit by removing a redundant pip command line. There's also a final error message as well if `pip` fails.
Before (success):
Before (error):
After (success):
After (error):

Improve init command

---

cmd/init.go

Setting this prevents the venv uninintialized warning in situations where the `init` command is run from within another one. Mainly this prevents the warnings from appearing during `trellis new`.

Set VenvInitialized within init command

---

trellis/complete.go
trellis/complete_test.go

https://github.com/roots/trellis-cli/pull/146 broke autocompletion by bumping the `complete` package version which included this change: https://github.com/posener/complete/pull/102.
Previously this worked around the off-by-one error, but after it was fixed, we were off by one 🙃 
This also refactors the completion tests to be more integration-style tests that would have caught this breaking change by running completions through the full CLI execution.

Fix CLI autocompletion

---

cmd/alias_test.go
cmd/cmd_test.go
cmd/db_open_test.go
cmd/deploy_test.go
cmd/dot_env_test.go
cmd/down_test.go
cmd/exec_test.go
cmd/galaxy_install_test.go
cmd/init_test.go
cmd/new_test.go
cmd/provision_test.go
cmd/rollback_test.go
cmd/ssh_test.go
cmd/up_test.go
cmd/valet_link_test.go
cmd/vault_decrypt_test.go
cmd/vault_edit_test.go
cmd/vault_encrypt_test.go
cmd/vault_view_test.go
cmd/venv_hook_test.go
main.go
trellis/complete_test.go
trellis/detector.go
trellis/detector_test.go
trellis/hosts_test.go
trellis/mock_detector.go
trellis/trellis.go
trellis/trellis_test.go

Refactor that improves the `NewTrellis` constructor with more flexible options and eliminates the need to manually create a (confusingly named) `Project` instance too. This enables a simpler `NewMockTrellis` constructor which sets the mock detector as well.

Refactor Trellis constructor

---

trellis/cli_config.go
trellis/trellis.go
trellis/trellis_test.go

Loads a `.trellis/cli.yml` config file if it exists for _per_ project configuration. Initially this config has no supported options.

Add CLI config file

---

cmd/open.go
cmd/open_test.go
cmd/valet_link.go
main.go
trellis/cli_config.go
trellis/config.go
trellis/testdata/trellis/.trellis/cli.yml
trellis/trellis.go
trellis/trellis_test.go

Fixes #76 
`trellis open` is a way to easily open user-defined project specific "shortcuts" (usually URLs).
By default it opens the main site's canonical development URL in your default web browser. Any additional shortcuts can be defined in the CLI config in `.trellis/cli.yml` as a simple map of name to value.
For example:
```yaml
open:
sentry: https://myapp.sentry.io
```

Add open command

---

cmd/deploy.go
cmd/deploy_test.go
cmd/provision.go
cmd/provision_test.go
cmd/rollback.go
cmd/rollback_test.go

Fixes #230
`--verbose` translates to Ansible's full verbose mode of `-vvvv`

Add verbose option for Ansible commands

---

cmd/init.go
cmd/init_test.go
cmd/new.go
main.go

`--force` deletes the existing virtualenv first instead of just running `pip install`.

Add force option to init

---

cmd/key_generate.go
cmd/key_generate_test.go
cmd/spinner.go
main.go

`trellis key generate` does the following:
1. creates a public/private SSH keypair using the Ed25519 algorithm
2. private key is created in $HOME/.ssh (by default)
3. public key is moved to `trellis/public_keys`
4. a GitHub secret is created for the private key on the current repo
5. a GitHub deploy key is created for the public key on the current repo
6. optionally provisions the server to ensure the public key is added and active
This command helps to setup a deployment process from a CI/CD platform like GitHub Actions which requires a deploy specific SSH key.
To accomplish this, it relies on the GitHub CLI being installed to take care of all the GitHub integration.
Output:

Add key generate command

---

cmd/key_generate.go
cmd/key_generate_test.go

`key generate` is meant to be used to setup GitHub actions for continuous deployment, which also requires setting SSH known hosts but that part was missing.
This automates using `ssh-keyscan` and setting the `TRELLIS_DEPLOY_SSH_KNOWN_HOSTS` secret for all Ansible hosts.

Set known hosts secret during key generation

---

cmd/key_generate.go

Fail earlier with more helpful error messages if the `gh` command isn't found or the auth status fails.

Improve GH cli detection/handling

---

trellis/virtualenv.go

Previously `virtualenv` was used if found. Instead we'll default to `python3` if available to ensure that Python 3 is used whenever possible over Python 2.

Give python3 precedence for venv

---

cmd/init.go
cmd/new.go
trellis/virtualenv.go

Adds more verbose and actionable error output when trellis-cli either can't install virtual, or more commonly, fails to create a virtual environment. The command used to create the venv is also included now for better debugging.
This also prevents `new` from continuing to create a new project if the initialization process fails. If the venv wasn't created successfully, dependencies won't be installed which will just lead to more errors (and more confusion).
Example output before:
```plain
Creating virtualenv in /mnt/d/Projects/mytest.test/trellis/.trellis/virtualenv
Error creating virtualenv: exit status 1
ERROR! Unexpected Exception, this is probably a bug: cannot import name 'CollectionRequirement' from 'ansible.galaxy.collection' …
```

Improve init and virtual error messages

---

cmd/deploy.go
cmd/droplet_create.go
cmd/provision.go
cmd/rollback.go
cmd/ssh.go
cmd/vault_decrypt.go
cmd/vault_encrypt.go
cmd/vault_view.go
trellis/complete.go
trellis/complete_test.go

Previously autocomplete would not work for positional arguments if any flags/options were present.
Example: `trellis provision --verbose pro`
The environment argument ("prod") would not be autocompleted. This was because of the predict functions which would act on `args.Completed`, and unfortunately, the complete package _includes_ flags in that array.
This solution passes in the command's flag set and uses that to parse the args. Now the predict functions acts on the positional args only, not the full set of completed args.
Opened an upstream issue since having to do this workaround seems complex and unnecessary: https://github.com/posener/complete/issues/146

Improve positional argument autocomplete when flags present

---

cmd/alias.go

Hides Ansible playbook output (since it's an implementation detail) and uses a spinner since it can take a few seconds.
@TangRufus should we just append this to `wp-cli.local.yml` automatically?

Improve alias command output

---

cmd/init.go
trellis/virtualenv.go
trellis/virtualenv_test.go

Previously trellis-cli tried to fallback to installing virtualenv if no other method was found. Turns out this was completely broken!
Since it's a complicated feature to offer, and users should really install it manually themselves, this feature is being removed entirely for now.
This also improves the existing `python3 -m venv` detection feature by adding an additional check to make sure it actually exists. This catches an edge case for Ubuntu/Debian/WSL users because their python3 package does not include venv.
Now those users will be shown an error letting them know what needs to be done.

Remove virtualenv install fallback

---

cmd/key_generate.go
cmd/key_generate_test.go

The last step in the `key generate` command is using `ssh-keyscan` to set the known hosts. It was fairly broken and the error handling didn't help to identify the problem.
Instead of scanning all hosts from a single command, this runs once per host to ensure one bad host doesn't prevent the good ones from succeeding. The error message also includes the hosts it tried to scan.
Finally, the ansible command to gather hosts has been improved by omitting development hosts.

Fix ssh-keyscan error handling in `key generate` command

---

trellis/trellis.go

1. make it more obvious this message would commonly appear for using trellis-cli on an existing project
2. mention it can be ignored if users want to manage dependencies manually

Improve the un-initialized warning message

---

cmd/galaxy_install.go
cmd/new.go
github/main.go
github/main_test.go

Fixes #262
This improves failure modes and error handling during the `new` command while creating a new project. Previously it was too easy for transient network failures to break a key part in the project creation process.
And even worse, the project would continue onto as is no failure happened.
Now every step has proper error handling that is checked, and in the case of a error, the process is stopped with a more helpful error message.

Improve failure modes during new project creation

---

cmd/key_generate_test.go
cmd/venv_hook_test.go
trellis/complete_test.go
trellis/virtualenv_test.go

Inspired by https://github.com/roots/trellis-cli/pull/264
This automatically restores the value to its original value in Cleanup

Use built-in testing.Setenv

---

Dockerfile

This also switches to pip for Trellis dependency management to ensure the proper versions of Ansible are installed.
Note: I already updated the docker images using this Dockerfile, just forgot to commit this.
cc @TangRufus

Update Dockerfile: go 1.17, bullseye, python3

---

cmd/key_generate.go
cmd/key_generate_test.go

In hindsight, trellis-cli will never be able to automatically determine the SSH known hosts without manual intervention. This approach asks the user for input through a prompt with the default value provided by the
list of hosts parsed from Ansible. It's hopefully the best of both worlds.
Note: the prompt library we're using doesn't allow for multi-select, so this uses a good ol' comma-separated string for multiple hosts.

Fixes #259 - use manual input for known hosts in `key generate` cmd

---

cmd/ad_hoc_playbook.go
cmd/alias.go
cmd/alias_test.go
cmd/db_open.go
cmd/db_opener_sequel_ace.go
cmd/dot_env_test.go
cmd/droplet_create.go
cmd/key_generate_test.go
cmd/new.go
github/main.go
plugin/finder.go
plugin/finder_test.go
trellis/config.go
trellis/detector_test.go
trellis/hosts_test.go
trellis/testing.go
trellis/trellis.go
trellis/trellis_test.go
trellis/vault.go
trellis/virtualenv.go
update/main.go
update/main_test.go

All the `io/ioutil` functions used in trellis-cli are obsolete now since they either just call the replacement method in its implementation, or the replacement is a better choice (as of Go 1.16 and 1.17).

Remove all ioutil usage

---

cmd/new.go

https://github.com/roots/trellis-cli/pull/263 broke this output a little bit. Instead of the version number, it outputs the string representation of the Go struct.

Fix version output for new projects

---

trellis/virtualenv.go

Fixes #281
It's not possible to rename/move a file across filesystems. Instead of renaming, this copies the file contents over instead.

Fix cross-link bug for virtualenv

---

cmd/check.go

Since Python 3 is required now, this should run the `python3` command instead of `python`.

Update python check command to python3

---

cmd/key_generate.go

Closes #286 
I have tested this with specifying: no repo (works as it did before), with an existing repo (works as intended by #286) and with non-existing repo.
For the non-existing repo, `gh api` returns `failed to fetch public key: HTTP 404: Not Found (https://api.github.com/repos/xxx/xxx/actions/secrets/public-key)` and is printed to console by existing `fmt.Errorf`.

Add GitHub secret and deploy key to specified `--repo`

---

trellis/virtualenv.go
trellis/virtualenv_test.go

https://github.com/roots/trellis-cli/pull/282 migrated from moving files to copying the contents, but it was broken (the order of arguments in `io.Copy` was wrong).
This fixes the file updating and simplifies the code by just using a buffer instead of temp files since we're not actually moving files.

Fix virtualenv shebangs updating

---

cmd/venv_hook.go
cmd/venv_hook_test.go

Fixes #295 
This removes the explicit wrapping of env values in double quotes and just relies on the `shellescape` library. Before it could result in double quoting (eg: export PATH="'/path/to folder/bin'").

Fix venv hook shell escaping

---

cmd/alias.go
cmd/files/playbooks/alias_template.yml.j2
cmd/testdata/expected/alias/wp-cli.trellis-alias.yml

Defaults to including the local env in `trellis alias` to include the Vagrant development environment.
For proper SSH support, this defaults to using the _main host_ which is what Trellis configures Vagrant to use as an SSH alias name (in your SSH config).
For non-Vagrant users, or any other non-default setup, `--skip-local` can be used to maintain the old behaviour.

Add local env support to alias cmd

---

cmd/alias.go
cmd/db_open.go
cmd/dot_env.go
cmd/vault_decrypt.go
cmd/vault_encrypt.go

Fixes #300 
This improves failure handling and output for two types of commands:
1. ones that use ad hoc playbooks
2. vault related
In both cases trellis-cli wasn't outputting useful error output from the underlying Ansible commands making it harder to troubleshoot.
The solution is to capture the output and conditionally display the error output when the underlying command fails.

Improve failure output for commands

---

cmd/new.go
github/main.go

Improve error handling and error messages when using the GitHub API to download Trellis and Bedrock.
This will pass through actual GitHub HTTP error responses for non-200 status codes. This is helpful to debug rate limit or authentication issues.
Note: trellis-cli should probably support a GitHub API auth token eventually, but this helps for now.

Fixes #309 - Better GitHub API error messages

---

trellis/cli_config.go
trellis/cli_config_test.go
trellis/trellis.go
trellis/trellis_test.go

Setting `ask_vault_pass` to true will make Ansible always prompt for the Vault password _instead_ of reading it from the `vault_pass_file` (specific in `ansible.cfg`).
This is done by setting the `ANSIBLE_ASK_VAULT_PASS` environment variable to `true`.

Fix #271 - Add ask_vault_pass config setting

---

trellis/detector.go
trellis/detector_test.go

This makes the project detector more flexible and less strict by dropping the `site` folder requirement. Previously the detector would only recognize the recommended folder structure when not directly inside a `trellis` folder. Your project would have to be structured like this:
```plain
example.com/       # → Root folder for the project
├── trellis/       # → Your server configuration (a customized install of Trellis)
└── .trellis/  # → trellis-cli config directory
└── site/          # → A Bedrock-based WordPress site
└── web/
```
`site` was required to limit false positives but isn't necessary due to the other requirement for the `.trellis` config directory.
By dropping the `site requirement`, this means trellis-cli will work better in two other known folder structures:
* where the …

Project detection: drop site folder requirement

---

cmd/droplet_create.go
digitalocean/main.go

Adds support for both ed25519 and rsa SSH keys. Previously this used `~/.ssh/id_rsa.pub` as the default `ssh-key` option value which forced users with ed25519 keys to manually specify the key path.
Now trellis-cli will check both `~/.sss/id_ed25519.pub` and `~/.sss/id_rsa.pub` keys by default.
This also improves failure handling and output of SSH key related functionality including outputting the path of the key being used to make it more obvious.

droplet create command: Support ed25519 SSH keys

---

cmd/droplet_create.go
cmd/droplet_create_test.go
cmd/droplet_dns.go
cmd/droplet_dns_test.go
digitalocean/client.go
digitalocean/digitalocean.go
dns/dns.go
main.go
trellis/config.go
trellis/config_test.go

`droplet dns` will automatically create DNS records for all the hosts that exist on the wordpress site for an environment.
This includes multiple sites, canonical hosts, and all redirects. With a single command you can be sure that the DNS records are up to date and ready for SSL certificates as well.
```plain
Usage: trellis droplet dns [options] ENVIRONMENT
Creates DNS records for all WordPress sites' hosts in an environment.
DNS records (type A) will be created for each host that all point to the
server IP found in the environment's hosts file (eg: 'hosts/production');
the host IP can be manually overriden if need be.
-------------------------------------------------------------------------------
Note: this command assumes your domain's DNS is managed by DigitalOcean and the
nameservers …
```

Add `droplet dns` command to create DNS records

---

cli_config/cli_config.go
cmd/deploy.go
cmd/deploy_test.go
trellis/trellis.go

Closes #335
Deploying to the development environment isn't needed by default since most local development environments sync/share site files automatically (like Vagrant does).
Running `trellis deploy development` can actually break a WordPress so this prevents it by default.
If someone is using a non-standard dev setup and does need to deploy (maybe to a remote cloud dev server?), a CLI config setting can be enabled to allow it.

Prevent deploys to development by default

---

README.md
cmd/logs.go
cmd/logs_test.go
cmd/ssh.go
cmd/ssh_test.go
command/testing.go
main.go
trellis/ssh.go

Closes #5
```plain
Usage: trellis logs [options] ENVIRONMENT [SITE]
Tails the Nginx log files for an environment.
Automatically integrates with https://goaccess.io/ when the --goaccess option is used.
View production logs:
$ trellis logs production
View access logs only:
$ trellis logs --access production
View error logs only:
$ trellis logs --error production
View logs in goaccess:
$ trellis logs --goaccess production
Pass flags to goaccess:
$ trellis logs --goaccess-flags="-a -m" production
View the last 50 log lines (-n corresponds to tail's -n option):
$ trellis logs -n 50 production
Arguments:
ENVIRONMENT Name of environment (ie: production)
SITE        Name of site (ie: example.com)
Options:
--access          Show access logs only
--error           Show error logs only
-g, …
```

Add logs command to view/tail Nginx log files

---

cmd/init.go

Fixes #306
The `init` command can be slow during the `pip install` step depending on network connections, first projects, or uncached dependencies. Since the output was hidden behind a spinner, it's not obvious what's happening during these situations.
This will switch to verbose mode showing `pip install`'s stdout to provide more information and a sign of progress most importantly.

Switch to verbose output when init command is slow

---

cmd/ssh.go
cmd/ssh_test.go

Flags for the ssh command weren't parsed before and effectively ignored/not supported.

Fix ssh cmd flags

---

cli_config/cli_config.go
cmd/db_open.go
cmd/db_opener_factory.go
cmd/db_opener_factory_test.go
cmd/db_opener_sequel_ace.go
cmd/db_opener_sequel_ace_test.go

Lets you set a default database app used in the `db open` command so the `--app` flag doesn't need to be manually set every time.
Also adds `db open` command autocompletion which was missing.

Add database_app CLI config option

---

cmd/db_open.go

Displays the output from the playbook to help with troubleshooting. Without this the command is essentially a blackbox with no visibility into what went wrong.

Improve db open error cases

---

cmd/alias.go
cmd/key_generate.go
cmd/open.go
cmd/vm_delete.go
cmd/vm_shell.go
cmd/vm_start.go
cmd/vm_stop.go
trellis/trellis.go
trellis/trellis_test.go

Always uses the first/main site name as the default instead of erroring if there's multiple dev sites.

Fix default VM name

---

pkg/lima/files/config.yml
pkg/lima/instance.go
pkg/lima/instance_test.go
pkg/lima/manager.go

* Only output `portForwards` if any exist
* Delete VM config on `vm delete`

Lima config updates

---

cmd/alias.go
cmd/db_open.go
cmd/deploy.go
cmd/dot_env.go
cmd/provision.go
cmd/vm.go
pkg/ansible/playbook.go

Automatically sets Ansible's inventory (`--inventory-file` option) in development based on the type of VM detected.
trellis-cli's Lima based VM gets priority over Vagrant by default if both inventory files are detected.

Set development inventory file based on VM

---

cmd/db_open.go

The `development` environment is probably the most common usage for `db open` so this makes it the default.

db open: default to development

---

trellis/trellis.go

Setting `virtualenv_integration: false` still resulted in the venv warning message being displayed even though the error message says it would disable it.
Reported in https://discourse.roots.io/t/introducing-lima-to-trellis-for-faster-local-development/24928/37?u=swalkinshaw

Fix virtualenv_integration config setting

---

cmd/provision.go
cmd/vm_shell.go
main.go
pkg/lima/manager.go
pkg/vm/testing.go
pkg/vm/vm.go

Fixes #377
Sets the default working directory for `vm shell` to the project's _main_ site (eg: `/srv/www/example.com/current`). The 
default can be overridden with the `--workdir` flag.
cc @robrecord

Add workdir support to `vm shell`

---

README.md
cmd/open.go
cmd/open_test.go
main.go
trellis/trellis.go
trellis/trellis_test.go

Adds more supported config files. In order of precedence, the following paths will be loaded:
* `.trellis/cli.yml` - existing file, now considered deprecated
* `trellis.cli.yml` - new path
* `trellis.cli.local.yml` - optional local override config
This change is being done to allow the `.trellis` directory to be gitigored as it contains CLI generated files that are machine specific and should not be committed to Git.

Support new trellis.cli.yml config file

---

cmd/alias.go

In case other's like me don't know there's one built-in to Bedrock. I spent time wondering why the one I was putting above /site was being ignored.

Update alias.go output message

---

cmd/files/playbooks/alias_template.yml.j2
cmd/testdata/expected/alias/wp-cli.trellis-alias.yml

I don't _think_ the generated `wp-cli.yml` is compliant with the yml spec.
> The “@” (x40, at) and “`” (x60, grave accent) are reserved for future use.
> Reserved indicators can't start a plain scalar.
— [yaml spec (1.2.2)](https://yaml.org/spec/1.2.2/)
`yamllint` and vscode's default YAML checks report errors, so I think I might be on to something.
```txt
test.yml
1:1       error    syntax error: found character '@' that cannot start any token (syntax)
```

Fix use of reserved characters in wp-cli.yml

---

cmd/vault_decrypt.go
cmd/vault_decrypt_test.go
cmd/vault_edit.go
cmd/vault_edit_test.go
cmd/vault_encrypt.go
cmd/vault_encrypt_test.go
cmd/vault_view.go
cmd/vault_view_test.go
main.go
pkg/flags/string_slice_var.go

The `vault` commands weren't consistent and had weird quirks. This makes the commands consistent while providing better defaults and improved usability. Changes:
* `-f` (`--file`) replaces the existing `--files` flag is now supported on all 4 commands. The old `--files` was a comma separated string while the new `-f` can be used multiple times and will autocomplete files
* `-f` cannot be combined with a position `ENVIRONMENT` option on any command since it was confusing and inconsistent
* `vault view` and `vault edit` no longer require an argument. They will default to showing a select input UI to choose from a vault file.
* `vault encrypt` and `vault decrypt` no longer require an argument. Both will default to _all_ vault files.
Closes #356

Improve consistency and usability of Vault commands

---

cmd/vm_start.go
pkg/lima/instance.go
pkg/lima/instance_test.go
pkg/lima/manager.go
pkg/lima/manager_test.go

Fixes #421
Changes how the CLI generates and manages Lima VM configs to make changes like mounted directories be accurately reflected in Lima.
trellis-cli used to generate a config for Lima in
`.trellis/lima/{name}.yml` which was used for the initial creation of the VM. However, even when providing a config to `limactl create`, Lima creates a separate config in its managed directory (`$HOME/.lima/{name}/lima.yaml`).
This meant that any subsequent config changes in Trellis might only be persisted to the CLI's managed config (in `.trellis`), which would do nothing, instead of Lima's config.
For example, if you added a new site to Trellis (or changed the path to an existing one), you'd either have to delete the VM entirely and start over, or manually make the changes to Lima's config.
This …

Refactor Lima config management

---

trellis/trellis.go
trellis/trellis_test.go

Fixes a bug where the project CLI config (`trellis.cli.yml`) was only loaded if the CLI command was run from within the `trellis` directory.
The project CLI config file was being loaded _before_ the project `Path` was set which meant it wasn't found and loaded. Now it's loaded after the `Path` is set.
cc @MWDelaney thanks!

Fix CLI config file loading from directories outside of `trellis`

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml
README.md

Example: https://github.com/tangrufus/trellis-cli/releases/tag/v1.12.2-alpha.9 which build with https://github.com/tangrufus/trellis-cli/blob/a8091f35faa0e2eaed38d28de7ba2d723e267f8c/.github/workflows/release.yml
```console
$ wget https://github.com/tangrufus/trellis-cli/releases/download/v1.12.2-alpha.9/trellis_Darwin_arm64.tar.gz.sbom.json
$ wget https://github.com/tangrufus/trellis-cli/releases/download/v1.12.2-alpha.9/trellis_Darwin_arm64.tar.gz
$ tar -zxvf trellis_Darwin_arm64.tar.gz
$ gh attestation verify --repo tangrufus/trellis-cli trellis_Darwin_arm64.tar.gz
Loaded digest sha256:60472939603d4ab8120f99d3106cc89cb48db8e59464b53c7ba7ab7e8601a153 for file://trellis_Darwin_arm64.tar.gz
Loaded 2 attestations from GitHub API
✓ Verification succeeded! …
```

Add GitHub attestation

---

pkg/lima/files/config.yml
pkg/lima/instance_test.go

Lima v1.0.0 disabled this option by default but it's needed for Ansible which connects via SSH.

Enable Lima's loadDotSSHPubKeys SSH option

---

scripts/get

Fixes https://github.com/roots/trellis-cli/issues/490
The checksums file generated by goreleaser now includes the sbom.json attestion files which results in two lines like this:
```
88b16e7ae5acfcb21ffaa5ceec6f0c420d9b8574404fd9ad8fb444f60ce50afa  trellis_Darwin_arm64.tar.gz
1ff74331df023fc2b68e209fe12f16e8e9ca46ef498131a796f0d3939d38efc8  trellis_Darwin_arm64.tar.gz.sbom.json
```
This extra file with the same file prefix broke the checksum `grep` command since both lines were returned.
This updates the grep pattern to ensure the line ends in the expected archive name only. It also limits the results to 1 as a guarantee.

Fix install script

---

help.go
main.go

The `vm` commands are no longer marked as experimental and should be preferred over the Vagrant specific `up` and `down`, which are now marked as deprecated.
Note: Vagrant support in Trellis is _not_ deprecated, just these commands in the CLI. The `vm` commands use Lima so they aren't a direct replacement for Vagrant, but at this point Lima should be the default over Vagrant for macOS users at least since it offers a better experience.

`vm` commands are now recommended over `up`/`down`

---

README.md
cli_config/cli_config.go
cmd/vm_delete.go
cmd/vm_shell.go
cmd/vm_start.go
cmd/vm_stop.go
trellis/trellis.go

Relates to #514
~A WIP but I've run out of time today, hopefully will pick this back up this week. Pushing up as I'm not even sure this is the right approach or wanted functionality, any feedback welcomed.~
Edit: Have been using this locally for a couple of weeks, haven't hit any issues. Opening this up for review & approval after a [nudge in Discourse](https://discourse.roots.io/t/trellis-vm-main-domain-subdomain-same-virtual-machine/29340/2?u=dalepgrant) from @jasperf.

Allow setting a custom instance name in Lima

---

.github/workflows/govulncheck.yml

Note: This job is failling because we actually have a vulnerability on the [`master` branch](https://github.com/roots/trellis-cli/tree/b934f4a20f4247cf537340b579e38bf545d9ffd7). See https://github.com/roots/trellis-cli/security/dependabot
```console
$ govulncheck -version
Go: go1.23.1
Scanner: govulncheck@v1.1.3
DB: https://vuln.go.dev
DB updated: 2024-09-06 20:44:22 +0000 UTC
$ git log --pretty=format:'%h %B' -n 1
b934f4a Merge pull request #466 from roots/go-1.23.1
Go 1.23
$ govulncheck -test -show verbose ./...
Scanning your code and 255 packages across 49 dependent modules for known vulnerabilities...
Fetching vulnerabilities from the database...
Checking the code against the vulnerabilities...
=== Symbol Results ===
Vulnerability #1: GO-2024-2698
Archiver Path Traversal vulnerability …
```

GitHub Actions: Add `govulncheck`
