roots/trellis-cli

- cmd/check.go
- cmd/new.go
- go.mod
- go.sum
- main.go
- trellis/requirement.go
`trellis check` will check if the required dependencies are met or not
> Add check command for requirements

- cmd/vault.go
- cmd/vault_decrypt.go
- cmd/vault_decrypt_test.go
- cmd/vault_edit.go
- cmd/vault_edit_test.go
- cmd/vault_encrypt.go
- cmd/vault_encrypt_test.go
- cmd/vault_view.go
- cmd/vault_view_test.go
- main.go
These commands mirror the main ones available from `ansible-vault`:
* `vault encrypt`
* `vault decrypt`
* `vault view`
* `vault edit`
> Add vault commands

- cmd/ssh.go
- cmd/ssh_test.go
- main.go
- trellis/config.go
- trellis/trellis.go
`ssh ENVIRONMENT SITE` will connect via SSH to the main canonical host
from the SITE specified (defaults to first site).
For now `production` is hardcoded to the `admin` user and `development`
uses `vagrant`.
> Add ssh command

- cmd/valet.go
- cmd/valet_link.go
- cmd/valet_link_test.go
- go.sum
- main.go
- trellis/complete_test.go
- trellis/testdata/trellis/group_vars/valet-link/wordpress_sites.yml
```sh-session
$ trellis-cli valet --help
Usage: trellis valet <subcommand> [<args>]
Subcommands:
link    Link the local_path directories to Valet
$ trellis-cli valet link --help
Usage: trellis valet link [options] [ENVIRONMENT=development]
Link the local_path directories to Valet
See https://laravel.com/docs/master/valet#the-link-command for more information.
Options:
-h, --help  show this help
$ trellis-cli valet link
Linking environment development...
Linking site typist.tech...
Running command => valet link --secure typist
A [typist] symbolic link has been created in [/Users/me/.config/valet/Sites/typist].
Restarting nginx...
The [typist.test] site has been secured with a fresh TLS certificate.
✓ Site typist.tech linked
Linking site third.second.com...
Running command => valet link …
```
> Add `valet link` command

- cmd/new.go
This will make it easier to create projects non-interactively. It's also another solution for https://github.com/roots/trellis-cli/issues/31.
> Add options to new command to bypass prompts

- cmd/new.go
- cmd/new_test.go
Eventually this command needs better integration tests, but for now we can at least test `askDomain`. This also identified a needless conditional which was removed.
> Add some tests for `new` cmd

- cmd/cmd_test.go
- cmd/command.go
- cmd/ssh.go
- cmd/ssh_test.go
- cmd/vault_edit.go
- cmd/vault_edit_test.go
- go.mod
- go.sum
- main.go
This lets us actually test what's called at least
> Refactor syscall usage + add ssh and vault edit command tests

- github/main.go
Something bad could happen when reading the body...
> Check return value of ioutil.ReadAll

- cmd/info.go
See: https://github.com/roots/trellis-cli/pull/84
> Looping over keys doesn't need _

- README.md
> Readme: Document install script arguments

- README.md
Copied from https://github.com/heroku/homebrew-brew/blob/f4776ab5b43c531a2b1047a66cd45d1224031d46/Formula/heroku.rb#L18-L33
> Readme: Update instruction for homebrew shell autocompletions

- cmd/droplet_create.go
The environment positional argument is required
> Fix droplet create argument validation

- cmd/provision.go
It took me a little while to find the syntax for multiple arguments. And more than once... I think this might make it a little clearer.
> Update provision command help text

- README.md
windows instructions were missing for manual install
> add windows installation instructions

- cmd/vault_encrypt.go
https://github.com/roots/trellis-cli/blob/b7dd0419dcaa474e44820f77ba283322e932437d/cmd/vault_encrypt.go#L65-L69
See: https://discourse.roots.io/t/unable-to-encrypt-multiple-files-using-trellis-cli/21003
> VaultEncryptCommand: Fix usage examples

- cmd/up.go
This replaces the existing `withGalaxy` option (which defaulted to `false`) to the inverse `noGalaxy` option that defaults to `true`.
Galaxy install was skipped by default before because Vagrant's integration always run the full `ansible-galaxy install` even if the roles were already installed which was annoying and slow.
But since trellis-cli has a much improved `galaxy install` command, this runs that by default now. If you truly do want to skip this, then supply the `--no-galaxy` option.
> Run galaxy install before up cmd by default

- cmd/xdebug_tunnel_close.go
- cmd/xdebug_tunnel_close_test.go
- cmd/xdebug_tunnel_open.go
- cmd/xdebug_tunnel_open_test.go
- main.go
Replicates the functionality in https://github.com/roots/trellis/blob/master/bin/xdebug-tunnel.sh
> Add xdebug-tunnel open and close commands

- cmd/init.go
pip being outdated can cause problems with dependencies. Ensure pip is up to date is the easiest way of avoiding any issues that can be at least.
Example of an issue this would fix: https://discourse.roots.io/t/trellis-cli-error-installing-dependencies-on-new-project-cryptography-package/22086/8
> Upgrade pip during init

- cmd/key_generate.go
> Skip provisioning after generating keys

- cmd/key_generate.go
- cmd/up.go
> Use `--repo` when setting known hosts secret

- cmd/files/playbooks/alias_template.yml.j2
> Support non-default public_path in Alias cmd

- cmd/alias.go
- cmd/db_open.go
- cmd/db_open_test.go
- cmd/deploy.go
- cmd/deploy_test.go
- cmd/dot_env.go
- cmd/playbook.go
- cmd/provision.go
- cmd/provision_test.go
- cmd/rollback.go
- cmd/rollback_test.go
- cmd/xdebug_tunnel_close.go
- cmd/xdebug_tunnel_close_test.go
- cmd/xdebug_tunnel_open.go
- cmd/xdebug_tunnel_open_test.go
- pkg/ansible/playbook.go
- pkg/ansible/playbook_test.go
Adds a new `Playbook` struct for easier and more normalized `ansible-playbook` command args generation.
> Refactor playbook usage

- README.md
- cli_config/cli_config.go
- pkg/lima/ubuntu.go
- trellis/trellis.go
~~Currently blocked by the ondrej/php PPA missing a couple of extensions~~
Ref https://github.com/roots/trellis/pull/1519
Close #444
> Ubuntu 24.04 support

- cmd/logs.go
- cmd/ssh.go
> Fix autocomplete args for logs and ssh commands

- main.go
GitHub CLI does this and it's a good idea. So I'm stealing it
> Add GitHub release link to --version
